### ISSUE TITLE
Can't access deleted vods

### ISSUE THREAD

**Issue by youngkiller1988** [TwitchRecover/TwitchRecover#127]
the program just closes no matter what i do

**Comment by TheYoungCormier** [comment]
https://streamscharts.com updated the URL's for streamer vods which causes the code to become invalid due to the current regex matching used in the code.

Use the old URL format: https://streamscharts.com/twitch/channels/CHANNEL_NAME/streams/STREAM_ID

This will fix the closing of the application temporarily.. if https://streamscharts.com decides to change it so the old URL doesn't redirect to the new URL then the regex in the code will have to be changed.

Note: The above only works if the VOD is within the 60 day max window as indicated in the README.

**Comment by youngkiller1988** [comment]
> https://streamscharts.com updated the URL's for streamer vods which causes the code to become invalid due to the current regex matching used in the code.
> 
> Use the old URL format: https://streamscharts.com/twitch/channels/CHANNEL_NAME/streams/STREAM_ID
> 
> This will fix the closing of the application temporarily.. if https://streamscharts.com decides to change it so the old URL doesn't redirect to the new URL then the regex in the code will have to be changed.
> 
> Note: The above only works if the VOD is within the 60 day max window as indicated in the README.

thank you for the workaround

**Comment by TheYoungCormier** [comment]
do you mean by adding the start time time of the stream and entering the date format? If so you shouldn't need to do that because either way is going to end in the same result.

If a VOD isn't found its because of https://github.com/TwitchRecover/TwitchRecover/issues/68

OR 

The streamer did not save the VOD in which twitch cannot save it on the server because it wouldn't exist.
