### ISSUE TITLE
issue with clip recovery

### ISSUE THREAD

**Issue by jimlahey024** [TwitchRecover/TwitchRecover#148]
clip recovery stopped working so i checked wfuzz in command prompt and it gave me some sort of error and already tried reinstalling it also reinstalled python
![fde164d48591ed03e9464446d438cab0](https://user-images.githubusercontent.com/88507345/128398967-958b312f-ad4e-4c53-bdb7-47b3594126b5.png)

**Comment by Linden10** [comment]
Hmm...another person had an error like yours with clip recovery not working, though in their case it was stuck on "clip recovering" but you seem to have a different peculiar error.

Not sure why it's happening but...I have a compiled jar file of the incomplete 2.0 branch of Twitch Recover that has various fixes that the main one doesn't. I've been able to recover clips without any problem with it so I hope this file helps you out!

First make sure to have java installed, then to execute the jar file type in command "java -jar "DIRPATH/TwitchRecover.jar" or create a shortcut with the target being the same command.

If you need help, do ask and I'll try my best!
 [TwitchRecover_(1e05316)_jar.zip](https://github.com/TwitchRecover/TwitchRecover/files/6912395/TwitchRecover_.1e05316._jar.zip)

**Comment by Linden10** [comment]
If you're still having this problem, I figured out the issue and how to resolve it!
I already helped someone else with the same issue as you, so you can look at my reply [here](https://github.com/TwitchRecover/TwitchRecover/issues/144#issuecomment-904296550) on how to fix it.

In a sense, the problem lies with the wfuzz.ini file located in .config folder of your user profile.
It's corrupted so deleting it and running wfuzz fixes it. Again read my reply above for instructions on how to resovle it!

Your welcome! ^_^
