### ISSUE TITLE
Mp4 file disappeared

### ISSUE THREAD

**Issue by Veteranjr** [TwitchRecover/TwitchRecover#31]
Hi, i have been downloading a 2hour sub-only VOD using " Twitch.recover.exe " 

I chose to download it as an mp4 file in source and to save it at D:\Twitch Vods\Azox , after 1 hour of downloading it says "  File downloaded at : D:\Twitch\TwitchRecover-VOD-869727705.mp4

I can't find it where it's supposed to be saved and i don't have such file as D\Twitch\ . Can't find the .mp4 file anywhere, what have i been missing please ? Thanks !

**Comment by daylamtayari** [comment]
Ok so I know what the issue is, it is the space in the file path. 
When the scanner reads the input, it reads up to a space, so here in this case it reads `D:\Twitch`. 
I am going to add that to list of bugs to be fixed for the beta. 

In the meantime, please only input file paths without a space and for that file, try searching in your file explorer or using whatever file search tool you use.

**Comment by Veteranjr** [comment]
It worked, much thanks. Good luck !

**Comment by nalabdev** [comment]
Same thing happened to me, also because of the space. But, even though the folder path I set was in D:\ it installed the file somewhere in my C:\, because I now have 0 bytes left of space. 

I tried searching, but I didn't find the file, does anyone know where that file could possibly have went to?
