### ISSUE TITLE
When channel id changed, can't recover vod

### ISSUE THREAD

**Issue by A1sk** [TwitchRecover/TwitchRecover#40]
I used option 5--->1 both old channel id and new channel id

But vod recover didn't work well

How can recover vod when channel id is changed?

**Comment by A1sk** [comment]
https://twitchtracker.com/akakakaka_/streams/40842279390

previous name is akakakayoung

**Comment by daylamtayari** [comment]
You can still recover VODs from that channel. Since the channel name has been changed, you need to input the values manually.
Now for this VOD in question, you cannot recover it because it is no longer available on Twitch VOD servers which is not that surprising since it is a stream from around two months ago. I tried recovering streams of that streamer of a couple days after that stream you listed.

**Comment by daylamtayari** [comment]
Closing this issue since it is not an issue with the actual program but rather the VOD being no longer available on Twitch servers.
