### ISSUE TITLE
Very Early Deleted Vod - Can't play Playlist or Muted

### ISSUE THREAD

**Issue by tonyrojas2007** [TwitchRecover/TwitchRecover#42]
https://twitchtracker.com/willneff/streams/41540120062

Your input can't be opened:
VLC is unable to open the MRL 'https://dqrpb9wgowsf5.cloudfront.net/94917886c708bfa14658_willneff_41540120062_1612148453/chunked/%3C?xml%20version=%221.0%22%20encoding=%22UTF-8%22?%3E'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'https://dqrpb9wgowsf5.cloudfront.net/94917886c708bfa14658_willneff_41540120062_1612148453/chunked/%3CError%3E%3CCode%3EAccessDenied%3C/Code%3E%3CMessage%3EAccess%20Denied%3C/Message%3E%3CRequestId%3E6E00DC6F1BC5F1E2%3C/RequestId%3E%3CHostId%3Ej7KNNImAaF7JXSmRi1uxmY2raqx11ljUXXEQAOfxMp49fwr9r1EVVDnJxVzSE0D58/VhwNPlcFg=%3C/HostId%3E%3C/Error%3E'. Check the log for details.

-------

Please enter the stream analytics link (supports Twitch Tracker and Stream Charts): https://twitchtracker.com/willneff/streams/41540120062

NO RESULTS FOUND.
The VOD cannot be found on Twitch servers.

**Comment by daylamtayari** [comment]
There is nothing wrong with the program, the VOD simply cannot be found on any Twitch VOD servers so I am going ahead and close this issue but you can still respond if you still have any questions.

I also do not understand how the first part of your issue is related (this following part):

> Your input can't be opened:
VLC is unable to open the MRL 'https://dqrpb9wgowsf5.cloudfront.net/94917886c708bfa14658_willneff_41540120062_1612148453/chunked/%3C?xml%20version=%221.0%22%20encoding=%22UTF-8%22?%3E'. Check the log for details.
Your input can't be opened:
VLC is unable to open the MRL 'https://dqrpb9wgowsf5.cloudfront.net/94917886c708bfa14658_willneff_41540120062_1612148453/chunked/%3CError%3E%3CCode%3EAccessDenied%3C/Code%3E%3CMessage%3EAccess%20Denied%3C/Message%3E%3CRequestId%3E6E00DC6F1BC5F1E2%3C/RequestId%3E%3CHostId%3Ej7KNNImAaF7JXSmRi1uxmY2raqx11ljUXXEQAOfxMp49fwr9r1EVVDnJxVzSE0D58/VhwNPlcFg=%3C/HostId%3E%3C/Error%3E'. Check the log for details.
