### ISSUE TITLE
Recovering VOD creates thousands of 0 byte Files in %temp%

### ISSUE THREAD

**Issue by Disrupi** [TwitchRecover/TwitchRecover#483]
Hello

I have an issue while recovering the following vod

https://twitchtracker.com/murdercrumpet/streams/48301947421
https://d1m7jfoe9zdc1j.cloudfront.net/9eba705d6ed23948201e_murdercrumpet_48301947421_1681333200/chunked/index-dvr.m3u8

While downloading this vod it just generates thousands of 0 byte files in the %Temp% folder 
Ive had this issue occur a few times already in the past accross different Devices regardless of app version

**Comment by Disrupi** [comment]
<img width="683" alt="screenshot" src="https://user-images.githubusercontent.com/95573431/231720436-afd88ded-780f-4096-bcfb-377200121484.png">

it generated >10000 items within 10 sec of runtime

**Comment by ghost** [comment]
@Disrupi 

269 of 1534 segments are valid (17.54% of the VOD available)

Due to 17.54% of the vod being available... Only about 44.5 minutes is still available to watch/download.

See attached zip

[VodRecovery_murdercrumpet_48301947421.zip](https://github.com/TwitchRecover/TwitchRecover/files/11221391/VodRecovery_murdercrumpet_48301947421.zip)

You can download the vod from here -> https://gofile.io/d/NiZlTE

**Comment by Disrupi** [comment]
Cheers thank you for that
Do you know maybe the reason why only a small portion is available? 
Could it be that the channelowner has deleted the vod and the fragments that are there are remains that havnt been fully deleted yet?

**Comment by ghost** [comment]
@Disrupi 

I'm not sure of the specific reason however what you suggested is possible and may be the case.

**Comment by Disrupi** [comment]
@Shishkebaboo cheers thank you for the fast response 
Ticket can be closed, have a good one!
