### ISSUE TITLE
M3U8 won't play

### ISSUE THREAD

**Issue by hubiemighthavecooltoes** [TwitchRecover/TwitchRecover#51]
As stated in the 2.0 guide it said to make a new issue when a m3u8 won't play so here it is https://vod-secure.twitch.tv/09ec3cf7b48f4fd2f6b6_ilooklikelilbil_41662297486_1613026629/chunked/index-dvr.m3u8 it was able to get the link, but vlc just won't play the network stream. It shows up in th eplayslist just fine after clicking play, with the correct duration. The thing just won't play.

**Comment by daylamtayari** [comment]
This is because the individual files are deleted.
An M3U8 link is a playlist link which references all of the individual TS files which are the actual video files.
The playlist link is still up but all of the individual video files are deleted.
For example if you check https://vod-secure.twitch.tv/09ec3cf7b48f4fd2f6b6_ilooklikelilbil_41662297486_1613026629/chunked/0.ts you'll see that it is deleted.

**Comment by hubiemighthavecooltoes** [comment]
I thought this tool could recover deleted vods?
