### ISSUE TITLE
Question about deleted vods?

### ISSUE THREAD

**Issue by hubiemighthavecooltoes** [TwitchRecover/TwitchRecover#54]
When this tool recovers deleted vods, does it mean just deleted as in the time ran out on it, or manually deleted by the streamer. Because I made an issue yesterday about a certain vod ( a recent one) not playing and someone said its cuz the video files are deleted, but i thought this tool makes that not an issue. I'm just still confused why the vod can't be accessed?

**Comment by daylamtayari** [comment]
This tool recovers all types of deleted vods, whether they are expired or deleted by a streamer.
So first of all let me explain how VODs work. An M3U8 link/file of a VOD is the playlist file of the VOD. It contains all of the references to each of the individual video files which contain the actual video content.
What this tool does is it gets the required information and reverse engineers the file name of the VOD **playlist** file and then searches for it across a list of Twitch VOD servers. 

Now lately Twitch has also been fully deleting the playlist and also the video files server side when its deleted. There has been some times where the playlist file was not deleted (almost certainly because of a bug in twitch's deleting job) but the individual files were deleted. This means that when you input the M3U8 link of one of these VODs into a program like VLC, it will try and load a set of files which no longer exist if that makes sense.

Let me know if there is anything you want me to clarify or any other questions feel free.

**Comment by Adroxxx** [comment]
So does that mean that if I try to get an m3u8 file (through twitch tracker) and twitch recover doesn't export a link, the VOD is deleted for good and there is no way for me to obtain it?

**Comment by daylamtayari** [comment]
That means that there is no VOD available on any of the Twitch VOD servers that I know of (of which the list can be found in the [domains.txt](https://github.com/TwitchRecover/TwitchRecover/blob/master/domains.txt) file).
