### ISSUE TITLE
Deleted vod .m3u8 link isn't loading in VLC

### ISSUE THREAD

**Issue by antisocialspicyboi** [TwitchRecover/TwitchRecover#57]
Followed correct instructions on help page, script outputs .m3u8 file, unable to open in VLC.

No muted segments. Total stream length shows in VLC then is unable to load video

**Comment by daylamtayari** [comment]
My initial suspicion would be that while the playlist file is still up, the individual video segments are deleted resulting in VLC being unable to play it.
Could you share the M3U8 link?

**Comment by antisocialspicyboi** [comment]
That sounds about right. Ran twitch recover again and it seems like the
video files are gone. See if this works

https://vod-secure.twitch.tv/2a46e7280d52d74668c1_ham__litt_41684741198_1613187269/chunked/index-dvr.m3u8

**Comment by antisocialspicyboi** [comment]
https://vod-secure.twitch.tv/1f033267ce8daa28ecf6_ham__litt_41699069070_1613276587/720p60/index-dvr.m3u8

That should be it. What you're saying sounds about right, believe the vod was deleted on the 14th from an affiliate streamer, not partnered.

**Comment by daylamtayari** [comment]
Yeah the issue is what I suspected, it is because the individual video files are deleted.
For example the first video file: https://vod-secure.twitch.tv/1f033267ce8daa28ecf6_ham__litt_41699069070_1613276587/720p60/0.ts 
You can see that it has been deleted.

However, after some quick testing, it seems that not all of the video files have been deleted YET. You can still view parts at like 2/3+ hours. 

Since I was having issues skipping ahead using VLC, I 'unmuted' (option 10) the M3U8 (which downloads the M3U8 playlist file and sets the URL for each of the individual files so you can just open the file directly into VLC) which allowed me to skip ahead without any issues.

This is the most you are going to be able to recover.
