### ISSUE TITLE
CLI 1.2 windows. Cannot retrieve sub only vod

### ISSUE THREAD

**Issue by Eyegabry99** [TwitchRecover/TwitchRecover#72]
When i paste a streamtracker url for a sub only vod, i cannot see anything. It throws me an error saying "no successful results were found". I'll give you the link of the twitch tracker https://twitchtracker.com/alliance_hakis/streams/40527432381

**Comment by daylamtayari** [comment]
Looked into this and the issue is that this streamer changed his name between that stream and today which means that while the tool is trying to find the vod using his current name, they exist under the name he had at that stream. 
If you are trying to recover the VOD, you would simply just need to input the values manually using his old name.

However, if you are just trying to find the link to a sub only VOD, you can just use option 3 of the latest alpha which allows you to just input the twitch video link directly.

Also the two VODs from that stream are freely available and not sub only so I dont know why you are talking about them being sub only.
