### ISSUE TITLE
Hey, i have some problems.

### ISSUE THREAD

**Issue by grayestcat** [TwitchRecover/TwitchRecover#77]
Honestly, I am new to Github, i have no idea if this is the right place to ask for this kind of help. I also don't understand anything that the following screenshot says and i was hoping someone could help me with this thing.

![image](https://user-images.githubusercontent.com/79873763/109555888-c61c3d80-7ade-11eb-8f2e-8aa9dfc66c8c.png)
I am using ubuntu, The latest LTS version 
i am also new to ubuntu so please forgive me if i don't understand a lot of things.

thank you!

**Comment by daylamtayari** [comment]
Hello, this is indeed the right place to report this.

Can you screenshot or tell me what you entered which caused this error?

**Comment by grayestcat** [comment]
Hello! Thanks for answering that quickly.

I have first ran the jar file , then picked the 5th option.

Then i chose 1 (use a stream analytics link)

i copy pasted the link from the Twitch tracker website, like your example: https://twitchtracker.com/tayarics/streams/40715936990

Then i press enter and the error messages came up, or whatever it was. 
Hope this helps!

**Comment by daylamtayari** [comment]
Can you tell me which version of Java you are running? 

When I run the jar file on Windows and do exactly what you said, I don't have any issues but I will try it on ubuntu later today in case there is a particular issue that is unique to ubuntu.

**Comment by grayestcat** [comment]
Hello, yes i can do that. i have openjdk version "11.0.10". i hope this works.

**Comment by daylamtayari** [comment]
Hello, sorry for the late reply, I have been extremely busy this past week. 
So I just tested this on ubuntu 20.04 lts using the same jdk as you, `openjdk 11.0.10` and I had no issues whatsoever.
Try maybe checking your installation and making sure its correct (using the hash and gpg signatures provided under the release) or redownloading it, but whatever it is, its an issue on your end.

I am going to close this issue since this is not an issue with the program itself but feel free to continue answering below, I will still be reading and answering your comments.

**Comment by grayestcat** [comment]
i redownloaded it and it worked. thanks!
