### ISSUE TITLE
Enhancement for help to find errors more easy

### ISSUE THREAD

**Issue by szereka** [TwitchRecover/TwitchRecover#85]
Would it be possible to have a switch that you can add to command line like "-debug"
To save a Log file in program start folder so IF Twitch adds more servers you can have an easier work to add server to config.

Just a tought for the future.

My Best Regards
Szereka

PS and Many Thanks for easy fix on my last Ticket. DS

**Comment by daylamtayari** [comment]
Yes, proper error handling is already in the works and when an error occurs, a very precise error code and message will be returned which will be accompanied with a wiki page with details and instructions on how to solve each error.
I'm going to close this issue since this is already something that is being worked on and is listed in the project board.
