### ISSUE TITLE
Problems with obtaining the m3u8 link

### ISSUE THREAD

**Issue by enzoafif** [TwitchRecover/TwitchRecover#86]
I'm having some problems obtaining the m3u8 link, whenever I paste the twitch tracker link and press enter the program just crashes (this is link -> https://twitchtracker.com/cellbit/streams/41096500317) i have tried it with both the 1.2 version and the 2.0 version

**Comment by Vinger2610** [comment]
Having the same issue hith that VOD, in 1.2 no results are found, in 2.0 it just crashes.

**Comment by enzoafif** [comment]
That's weird, i have tried obtaining the m3u8 link from that channel before, and i"ve never had any issues before

**Comment by daylamtayari** [comment]
So the issue appears to be when the program tries to recover Twitch Tracker links. 
I am looking into the exact reason why this is being caused right now.

**Comment by daylamtayari** [comment]
In the meantime you can use Streamscharts URLs which still work fine.
The corresponding streamscharts URL for that stream you linked is: https://streamscharts.com/twitch/channels/cellbit/streams/41096500317

**Comment by enzoafif** [comment]
Okay, thanks

**Comment by daylamtayari** [comment]
I believe I found the issue, Twitch Tracker has added a verification using cloudflare to their website which results in possible issues when trying to retrieve a twitch tracker link since the direct access isn't utilised.
While there are ways to go around this, I will look into seeing if they are worth implementing otherwise will simply continue supporting it unofficially because it does not fail for all users and also in case they ever change this.
