### ISSUE TITLE
VLC can't read this m3u8?

### ISSUE THREAD

**Issue by gajowastaken** [TwitchRecover/TwitchRecover#88]
Sorry to bother, but I attempted to recover a deleted vod from https://twitchtracker.com/young_office_chan/streams/41111041021, and the m3u8 that was pulled did not open in VLC or any other program to view m3u8s. Below is the m3u8 link that the 2.0 version created. Any help is appreciated.

https://vod-secure.twitch.tv/81e9118655683b79d474_young_office_chan_41111041021_1616360814/chunked/index-dvr.m3u8

**Comment by tbpom1003** [comment]
same issue here, I believe it's due to the twitch's changed VOD deletion rule. They started to delete the VOD right away. 
I am able to watch the m3u8 which is not deleted, but unsuccessful with any deleted VODs.

Here is the stream link and m3u8 I tried
https://streamscharts.com/twitch/channels/ppsomin93/streams/41227129405
https://d1m7jfoe9zdc1j.cloudfront.net/379b600d0798a205f820_ppsomin93_41227129405_1617122007/chunked/index-dvr.m3u8

**Comment by daylamtayari** [comment]
The issue with the VOD you linked is that while the playlist link is still available, the first few segments have being deleted by twitch.
I found how many of the first segments were deleted and fixed the playlist accordingly.
I attached the file to this reply, to get it to work, just edit the file name and remove the `.txt` part to make the file back into an `.m3u8` and then you can play it in VLC.
[TwitchRecover-M3U8-5460973.m3u8.txt](https://github.com/TwitchRecover/TwitchRecover/files/6255792/TwitchRecover-M3U8-5460973.m3u8.txt)

**Comment by charremdaikun** [comment]
hi, i have the same problem with this VOD : [](https://vod-secure.twitch.tv/ed9eae275855354b9d42_fafaninio_16357035381_3875799291/chunked/highlight-550845325.m3u8)

can you fixe this problem please
