### ISSUE TITLE
No results found or crashing

### ISSUE THREAD

**Issue by JJKrj** [TwitchRecover/TwitchRecover#91]
Whenever i try to get the link to a vod to paste it into vlc, it says no results found in 1.2. The programme just crashes after pasting the link in 2.0.  It used to work perfectly before and started acting up a couple of days ago. I have tried on 3 seperate windows machines, all with the same result. Please help?

![Schermopname (2)](https://user-images.githubusercontent.com/81964074/113568193-5b47b000-9610-11eb-9975-769c7c1a77ad.png)

**Comment by daylamtayari** [comment]
I believe I found the issue, Twitch Tracker has added a verification using cloudflare to their website which results in possible issues when trying to retrieve a twitch tracker link since the direct access isn't utilised.
While there are ways to go around this, I will look into seeing if they are worth implementing otherwise will simply continue supporting it unofficially because it does not fail for all users and also in case they ever change this.

**Comment by JJKrj** [comment]
What could be a way to go around it?

**Comment by JJKrj** [comment]
And the manual input doesnt seem to work either, any advice on how to get the links in another way? Love the tool btw
